### ISSUE TITLE
Order By ACF Field Issue

### ISSUE THREAD

**Issue by depus9** [iamntz/elementor-query-utils#1]
I am trying to order with acf field but not working properly

**Comment by iamntz** [comment]
Hey @depus9 can you provide more details about this?

What keys are you using, what type are those data, the key is within a repeater, what post type, what version of elementor, etc.

Please attach the [acf json](https://www.advancedcustomfields.com/resources/local-json/) here and a screenshot of the Elementor's query configuration panel.
